[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
solc_version = "0.8.24"
gas_reports = ["TokenVesting", "TokenVestingMerkle"]

[fmt]
bracket_spacing = true
line_length = 150
tab_width = 4
quote_style = 'double'
func_attrs_with_params_multiline = true

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }